import '@/lib/orpc.server'; // prerendering for ssr
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/lib/theme-provider';
import { AuthProvider } from '@/lib/auth-provider';
import { Providers } from '@/lib/query/providers';
import { Toaster } from '@/components/ui/sonner';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root layout that composes global providers, theming, and application chrome for every page.
 *
 * Wraps the app with authentication and UI providers, applies the Poppins font and antialiasing,
 * enables system-aware theming, and mounts global UI primitives (Providers and Toaster).
 *
 * @param children - The page content to render inside the global providers and theme.
 * @returns The root HTML element tree that wraps application pages with global providers and UI chrome.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>{children}</Providers>
            <Toaster closeButton position='top-center'/>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}